# Generated by Django 5.2.5 on 2025-08-10 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_id', models.CharField(max_length=100)),
                ('bm_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acc_id', models.CharField(max_length=100)),
                ('acc_link', models.URLField()),
                ('bm_client_id', models.CharField(max_length=100)),
                ('bm_client_name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('mb_admin_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.adminbm')),
            ],
        ),
    ]
