# Generated by Django 5.2.5 on 2025-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_adminbm_adaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=100),
        ),
    ]
