# Generated by Django 5.2.5 on 2025-08-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_adaccount_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdAccount',
        ),
    ]
