# Generated by Django 5.2.5 on 2025-08-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_adaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccount',
            name='bm_client_name',
        ),
    ]
