# Generated by Django 5.2.5 on 2025-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_adaccount_bm_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pending_accounts',
            field=models.IntegerField(default=0),
        ),
    ]
