# Generated by Django 5.2.5 on 2025-08-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_wallet_pending_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='pending_deposit',
            new_name='pending_deposits',
        ),
    ]
