# Generated by Django 5.2.5 on 2025-08-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_pending_deposit_wallet_pending_deposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='bm_client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adaccount',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
