# Generated by Django 5.2.5 on 2025-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_adaccount_bm_client_name_adaccount_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
