# Generated by Django 5.2.5 on 2025-08-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_adaccount_monthly_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=100)),
                ('acc_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='adaccount',
            name='mb_admin_reference',
        ),
        migrations.RemoveField(
            model_name='adaccount',
            name='bm_client_id',
        ),
        migrations.RemoveField(
            model_name='adaccount',
            name='bm_client_name',
        ),
        migrations.AddField(
            model_name='adaccount',
            name='bm_accounts',
            field=models.ManyToManyField(blank=True, to='dashboard.bmaccount'),
        ),
        migrations.DeleteModel(
            name='AdminBM',
        ),
    ]
