# Generated by Django 5.2.5 on 2025-08-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_bmaccount_remove_adaccount_mb_admin_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='pending_accounts',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='pending_deposits',
        ),
    ]
