# Generated by Django 5.2.5 on 2025-08-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_wallet_pending_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='adaccount',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='adaccount',
            name='total_spent',
        ),
    ]
