# Generated by Django 5.2.5 on 2025-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_adaccount_balance_remove_adaccount_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmaccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
