# Generated by Django 5.2.5 on 2025-08-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_bmaccount_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmaccount',
            name='status',
        ),
        migrations.AddField(
            model_name='bmaccount',
            name='type',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], default='add', max_length=10),
        ),
    ]
