# Generated by Django 5.2.5 on 2025-08-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_bmaccount_status_bmaccount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmaccount',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
