# Generated by Django 5.2.5 on 2025-08-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_bmaccount_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmaccount',
            name='type',
        ),
    ]
