# Generated by Django 5.2.5 on 2025-08-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_bmaccount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmaccount',
            name='request_type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('add', 'Add'), ('remove', 'Remove')], default='N/A', max_length=10),
        ),
    ]
