# Generated by Django 5.2.5 on 2025-08-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_bmaccount_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.TextField()),
                ('acc_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='adaccount',
            name='admin_bm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminbm'),
        ),
    ]
