# Generated by Django 5.2.5 on 2025-08-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_adminbm_adaccount_admin_bm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbm',
            name='acc_name',
            field=models.CharField(max_length=100),
        ),
    ]
