# Generated by Django 5.2.5 on 2025-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_adminbm_acc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbm',
            name='acc_id',
            field=models.CharField(max_length=100),
        ),
    ]
