# Generated by Django 5.2.5 on 2025-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_adminbm_acc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbm',
            name='acc_id',
            field=models.IntegerField(),
        ),
    ]
