# Generated by Django 5.2.5 on 2025-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_adminbm_acc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, default=127.0, max_digits=10),
        ),
    ]
