# Generated by Django 5.2.5 on 2025-08-29 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], default='increase', max_length=10)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ad_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.adaccount')),
            ],
        ),
    ]
