# Generated by Django 5.2.5 on 2025-08-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_topup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topup',
            new_name='TopupHistory',
        ),
    ]
