# Generated by Django 5.2.5 on 2025-09-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_rename_topup_topuphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbm',
            name='acc_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='trx_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='vendor_trx_id',
            field=models.CharField(max_length=100),
        ),
    ]
