# Generated by Django 5.2.5 on 2025-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_adminbm_acc_id_alter_deposittransaction_trx_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
