# Generated by Django 5.2.5 on 2025-09-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='method_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
