# Generated by Django 5.2.5 on 2025-09-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_paymentmethod_method_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
