# Generated by Django 5.2.5 on 2026-06-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('wallet_edit', 'Wallet Balance Edited'), ('rate_change', 'Dollar Rate Changed'), ('topup_increase', 'Top-up (Increase)'), ('topup_decrease', 'Top-up (Decrease Request)'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('user_created', 'User Created'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('user_deleted', 'User Deleted'), ('ad_account_created', 'Ad Account Created'), ('ad_account_activated', 'Ad Account Activated'), ('ad_account_deactivated', 'Ad Account Deactivated'), ('bm_added', 'BM Account Added'), ('bm_removed', 'BM Account Removed'), ('bm_approved', 'BM Account Approved'), ('payment_method_added', 'Payment Method Added'), ('payment_method_removed', 'Payment Method Removed')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BusinessExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('server', 'Server Costs'), ('marketing', 'Marketing'), ('salary', 'Salaries'), ('fb_api', 'Facebook API Costs'), ('software', 'Software/Tools'), ('maintenance', 'Maintenance'), ('other', 'Other')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('amount_bdt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(db_index=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='expense_receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_bdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('account_details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='include_in_profit_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manual_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='adaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='inactive', max_length=100),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='trx_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='adaccount',
            index=models.Index(fields=['user', 'status'], name='dashboard_a_user_id_83b8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='adaccount',
            index=models.Index(fields=['-start_date'], name='dashboard_a_start_d_0f6bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['user', 'status'], name='dashboard_d_user_id_50b57d_idx'),
        ),
        migrations.AddIndex(
            model_name='deposittransaction',
            index=models.Index(fields=['-created_at'], name='dashboard_d_created_ca71ee_idx'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessexpense',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='dashboard_a_timesta_77b0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity_type', '-timestamp'], name='dashboard_a_activit_37f6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['performed_by', '-timestamp'], name='dashboard_a_perform_324c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['target_user', '-timestamp'], name='dashboard_a_target__c37554_idx'),
        ),
        migrations.AddIndex(
            model_name='businessexpense',
            index=models.Index(fields=['-date'], name='dashboard_b_date_0c68be_idx'),
        ),
        migrations.AddIndex(
            model_name='businessexpense',
            index=models.Index(fields=['category', '-date'], name='dashboard_b_categor_1620ed_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', '-requested_at'], name='dashboard_w_status_a2b083_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', '-requested_at'], name='dashboard_w_user_id_d061ab_idx'),
        ),
    ]
