# Generated by Django 6.0.6 on 2026-06-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_activitylog_businessexpense_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('mobile_wallet', 'Mobile Wallet')], default='bank', max_length=20),
        ),
    ]
