# Generated by Django 6.0.6 on 2026-06-12 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_paymentmethod_method_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('deposit_pending', 'Deposit Pending'), ('topup_approved', 'Topup Approved'), ('topup_decrease_approved', 'Topup Decrease Approved'), ('ad_account_activated', 'Ad Account Activated'), ('ad_account_deactivated', 'Ad Account Deactivated'), ('bm_approved', 'BM Account Approved'), ('bm_removed', 'BM Account Removed'), ('wallet_updated', 'Wallet Updated'), ('general', 'General')], default='general', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_n_user_id_5c2164_idx'), models.Index(fields=['user', 'is_read'], name='dashboard_n_user_id_b572f4_idx')],
            },
        ),
    ]
