# Generated by Django 6.0.6 on 2026-06-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('viewer', 'Viewer'), ('regular', 'Regular User')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_view_dashboard', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_payments', models.BooleanField(default=False)),
                ('can_review_deposits', models.BooleanField(default=False)),
                ('can_manage_accounts', models.BooleanField(default=False)),
                ('can_edit_settings', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, default=110, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.userrole'),
        ),
    ]
