# Generated by Django 6.0.6 on 2026-06-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_userrole_user_dollar_rate_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('deposit_pending', 'Deposit Pending'), ('topup_approved', 'Topup Approved'), ('topup_decrease_approved', 'Topup Decrease Approved'), ('topup_pending', 'Topup Pending'), ('ad_account_activated', 'Ad Account Activated'), ('ad_account_deactivated', 'Ad Account Deactivated'), ('ad_account_pending', 'Ad Account Pending'), ('bm_approved', 'BM Account Approved'), ('bm_removed', 'BM Account Removed'), ('bm_pending', 'BM Pending'), ('withdrawal_pending', 'Withdrawal Pending'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('wallet_updated', 'Wallet Updated'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
