# Generated by Django 5.2.5 on 2026-06-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_line1', models.CharField(default='Scale Your Ads.', max_length=100)),
                ('hero_title_line2', models.CharField(default='Faster & Smarter.', max_length=100)),
                ('hero_subtitle', models.TextField(default='Get premium ad accounts for Facebook, TikTok & Google Ads. Top up instantly, manage everything from one dashboard.')),
                ('hero_badge_text', models.CharField(default='Trusted Ad Account Platform', max_length=100)),
                ('stat_users', models.CharField(default='500+', max_length=20)),
                ('stat_ad_spend', models.CharField(default='$2M+', max_length=20)),
                ('about_title', models.CharField(default='We Help Advertisers Run Ads Without Limits', max_length=150)),
                ('about_body1', models.TextField(default='Adgenx was founded by a team of performance marketers who were tired of getting ad accounts banned, restricted, or limited.')),
                ('about_body2', models.TextField(default='Our team manages every account personally — ensuring fast top-ups, zero downtime, and full transparency in every transaction.')),
                ('about_founded_year', models.CharField(default='2022', max_length=10)),
                ('about_stat_clients', models.CharField(default='500+', max_length=20)),
                ('about_stat_spend', models.CharField(default='$2M+', max_length=20)),
                ('about_stat_uptime', models.CharField(default='99%', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, default='8801XXXXXXXXX', max_length=30)),
                ('email_support', models.EmailField(blank=True, default='support@adgenx.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True, default='#')),
                ('telegram_url', models.URLField(blank=True, default='#')),
                ('tiktok_url', models.URLField(blank=True, default='#')),
                ('instagram_url', models.URLField(blank=True, default='#')),
                ('footer_tagline', models.CharField(default='Premium ad account management platform for Facebook, TikTok & Google Ads. Scale without limits.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('avatar_initials', models.CharField(help_text='2-3 letters shown as avatar, e.g. RK', max_length=3)),
                ('avatar_color', models.CharField(default='#4f46e5', help_text='Hex color for avatar background', max_length=7)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
