# Generated by Django 6.0.6 on 2026-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload logo image (max 2MB, PNG/JPG recommended)', null=True, upload_to='logos/'),
        ),
    ]
