# Generated by Django 6.0.6 on 2026-06-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_sitesettings_logo'),
    ]

    operations = [
    ]
